### ISSUE TITLE
XorShift64: Range() cast to signed integer causes out-of-range values to be returned

### ISSUE THREAD

**Issue by rotemdan** [Bunny83/Utilities#3]
Hi, I'm using some of your code in my program (found it via a Google search). I noticed that in `Range()` the cast to `(int)` sometimes causes out-of-range values to be returned, since in C# the modulus operation is sign sensitive (for example `-10 % 3 = -1`):
```cs
public int Range(int aMin, int aMax)
{
  return aMin + (int)Next() % (aMax - aMin);
}
```

In my own code, I changed it to:
```cs
public int Range(int aMin, int aMax)
{
  Debug.Assert(aMax > aMin);

  return aMin + (int)((uint)Next() % (aMax - aMin));
}
```
(Edit: I don't think this would work when `(aMax - aMin) >= 2^31` but I don't need such large ranges in my code)

**Comment by Bunny83** [comment]
Thanks for the issue report. Yes, this really is an issue I hadn't thought of. I fixed the method in [2bd5d8](https://github.com/Bunny83/Utilities/commit/2bd5d8a917bbd0d220a0c7296237ce47a486df58)

First I made a fix using tons of convoluted casts which got the job done, but didn't look nice and in the end carried out most of the calculations in higher datatypes anyways. So i simply implemented a long version which could use the full long range and implemented the int version just as a wrapper of the long version.

I added AggressiveInlining to most methods which should help with potential performance overhead, at least on some targets.
