### ISSUE TITLE
Can't read certain BMPs

### ISSUE THREAD

**Issue by hippogamesunity** [Bunny83/Utilities#5]
Hi! I was unable to load the attached BMP, tried with different settings.
[Game.zip](https://github.com/Bunny83/Utilities/files/8457484/Game.zip)

**Comment by Bunny83** [comment]
Well, there were a few typos and copy&paste errors. I've rewritten the header parsing and properly implemented all header types (V2, V3, V3Ext, V4, V5). So it now supports the V2 palette format and should handle the alpha mask and alpha values correctly. At least your image loads correctly.

**Comment by hippogamesunity** [comment]
I can confirm it works now.
I saw you're also working on a GIF loader. I've made my own GIF lib for Unity, here is the voucher in gratitude for your help. Unfortunately, I'm not a open-source fan =)

https://assetstore.unity.com/packages/tools/animation/power-gif-runtime-library-giphy-api-120039
ASV-C7NN-9HJX-F6FG-D6NU-LVUM
